name: CodeClimate coverage test
on: [push]
jobs:
    ReportCoverageReport:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-ruby@v1
              with:
                  ruby-version: '3.0.3'
            - run: |
                gem install bundler
                bundle install
                rspec spec/*_spec.rb
