name: CodeClimate coverage test
on: [push]
env:
    CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }} 
jobs:
    ReportCoverageReport:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-ruby@v1
              with:
                  ruby-version: '3.0.3'
            - name: Install dependencies
              id: deps
              run: |
                gem install bundler
                bundle install
            - name: CodeClimate before_script
              id: cc_before
              run: |
                curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
                chmod +x ./cc-test-reporter
                ./cc-test-reporter before-build
            - name: Test and generate report
              id: test
              run: |
                rspec spec/*_spec.rb
            - name: CodeClimate after_script on_failure
              id: cc_after_failure
              if: steps.test.outcome != 'success'
              run: ./cc-test-reporter after-build --exit-code 1
            - name: CodeClimate after_script on_success
              id: cc_after_success
              if: steps.test.outcome == 'success'
              run: ./cc-test-reporter after-build --exit-code 0
