name: CodeClimate coverage test
on: [push]
jobs:
    ReportCoverageReport:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-ruby@v1
              with:
                  ruby-version: '3.0.3'
            - name: Install dependencies
              id: deps
              run: |
                gem install bundler
                bundle install
            - name: Test and generate report
              id: test
              run: |
                  rspec spec/*_spec.rb
            - name: Upload report
              id: upload
              uses: paambaati/codeclimate-action@v3.0.0
              env:
                  CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
              with:
                  coverageLocations: |
                      ${{github.workspace}}/coverage/.resultset.json:simplecov
