name: CodeClimate coverage test
on: [push]
env:
    CC_TEST_REPORTER_ID: 24aa918abf203fe86bfe6e849fbe87dc0dd3a36a91f863d8330abd55438102a0
jobs:
    ReportCoverageReport:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-ruby@v1
              with:
                  ruby-version: '3.0.3'
            - name: Install dependencies
              id: deps
              run: |
                gem install bundler
                bundle install
            - name: CodeClimate before_script
              id: cc_before
              run: |
                curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
                chmod +x ./cc-test-reporter
                ./cc-test-reporter before-build
            - name: Test and generate report
              id: test
              run: |
                rspec spec/*_spec.rb
            - name: CodeClimate after_script
              id: cc_after
              run: |
                ./cc-test-reporter after-build --exit-code 0
